# Generated by Django 5.0 on 2024-06-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSchool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursePhoto',
            field=models.ImageField(blank=True, default='upload/defaultPhoto/defaultUserImg.jpeg', null=True, upload_to='upload/coursePhoto'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacherPhoto',
            field=models.ImageField(blank=True, default='upload/defaultPhoto/defaultUserImg.jpeg', null=True, upload_to='upload/teacherPhoto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='upload/defaultPhoto/defaultUserImg.jpeg', null=True, upload_to='upload/studentPhoto'),
        ),
    ]
