# Generated by Django 5.0 on 2024-06-18 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSchool', '0003_course_teacherdescription_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSchool.course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('videoUrl', models.FileField(upload_to='upload/videos/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSchool.section')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRelatedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('fileUrl', models.FileField(upload_to='upload/files/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eSchool.video')),
            ],
        ),
    ]
