# Generated by Django 5.0 on 2024-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSchool', '0004_remove_student_email_section_video_videorelatedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoUrl',
            field=models.FileField(upload_to='upload/videos/<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AlterField(
            model_name='videorelatedfile',
            name='fileUrl',
            field=models.FileField(upload_to='upload/files/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
