# Generated by Django 5.0 on 2024-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSchool', '0005_alter_video_videourl_alter_videorelatedfile_fileurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoUrl',
            field=models.FileField(upload_to=''),
        ),
    ]
