# Generated by Django 5.0 on 2024-06-18 10:44

import eSchool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSchool', '0006_alter_video_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseStudentsCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoUrl',
            field=models.FileField(max_length=255, upload_to=eSchool.models.video_directory_path),
        ),
        migrations.AlterField(
            model_name='videorelatedfile',
            name='fileUrl',
            field=models.FileField(max_length=255, upload_to=eSchool.models.file_directory_path),
        ),
    ]
